#Muhammad Harsya Permadi (202231024)

In [2]:
# Mengimpor library NumPy dan memberikan alias 'np'.
# NumPy digunakan untuk operasi numerik dan array multidimensi.
import numpy as np

# Mengimpor library Pandas dan memberikan alias 'pd'.
# Pandas digunakan untuk manipulasi dan analisis data tabular.
import pandas as pd

In [4]:
# Variabel `dataset` diinisialisasi dengan membaca data dari file CSV "K01_heart_disease.csv"
# menggunakan fungsi `read_csv` dari library Pandas (`pd`).
dataset = pd.read_csv("K01_heart_disease.csv")
# Menampilkan isi dari variabel `dataset` yang berupa DataFrame Pandas.
dataset

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [5]:
# Mengakses kolom 'Sex' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'Sex'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['Sex'].unique()


array(['M', 'F'], dtype=object)

In [6]:
dataset['ChestPainType'].unique()
# Mengakses kolom 'ChestPainType' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ChestPainType'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [7]:
dataset['RestingECG'].unique()
# Mengakses kolom 'RestingECG' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'RestingECG'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.

array(['Normal', 'ST', 'LVH'], dtype=object)

In [8]:
# Mengakses kolom 'ExerciseAngina' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ExerciseAngina'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['ExerciseAngina'].unique()

array(['N', 'Y'], dtype=object)

In [9]:
# Mengakses kolom 'ST_Slope' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ST_Slope'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [10]:
# Menampilkan informasi ringkas tentang DataFrame 'dataset'.
dataset.info

<bound method DataFrame.info of      Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]>

In [11]:
# Mengimpor LabelEncoder dari library sklearn.preprocessing
from sklearn.preprocessing import LabelEncoder

# Membuat objek LabelEncoder untuk setiap kolom kategorikal
le_sex = LabelEncoder() # Untuk kolom 'Sex'
le_resting_ecg = LabelEncoder() # Untuk kolom 'RestingECG'
le_exercise_angina = LabelEncoder() # Untuk kolom 'ExerciseAngina'
le_st_slope = LabelEncoder() # Untuk kolom 'ST_Slope'

# Mengubah data kategorikal menjadi numerik menggunakan Label Encoding
dataset['Sex'] = le_sex.fit_transform(dataset['Sex']) # Mengubah kolom 'Sex'
dataset['ChestPainType'] = le_sex.fit_transform(dataset['ChestPainType']) # Mengubah kolom 'ChestPainType'
dataset['RestingECG'] = le_resting_ecg.fit_transform(dataset['RestingECG']) # Mengubah kolom 'RestingECG'
dataset['ExerciseAngina'] = le_exercise_angina.fit_transform(dataset['ExerciseAngina']) # Mengubah kolom 'ExerciseAngina'
dataset['ST_Slope'] = le_st_slope.fit_transform(dataset['ST_Slope']) # Mengubah kolom 'ST_Slope'

In [12]:
dataset

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [13]:
dataset['Sex'].unique()
# Mengakses kolom 'Sex' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'Sex'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.

array([1, 0])

In [14]:
# Mengakses kolom 'ChestPainType' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ChestPainType'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['ChestPainType'].unique()

array([1, 2, 0, 3])

In [15]:
# Mengakses kolom 'RestingECG' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'RestingECG'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['RestingECG'].unique()

array([1, 2, 0])

In [16]:
# Mengakses kolom 'ExerciseAngina' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ExerciseAngina'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['ExerciseAngina'].unique()

array([0, 1])

In [17]:
# Mengakses kolom 'ST_Slope' pada DataFrame `dataset`.
# .unique() digunakan untuk mendapatkan nilai unik dari kolom 'ST_Slope'.
# Outputnya adalah array berisi nilai-nilai unik dalam kolom tersebut.
dataset['ST_Slope'].unique()

array([2, 1, 0])

In [18]:
# Variabel `x` menyimpan fitur-fitur (input) untuk model machine learning.
# `dataset.drop()` menghapus kolom 'HeartDisease' dari DataFrame `dataset`.
# `axis=1` menunjukkan bahwa yang dihapus adalah kolom.
# Jadi, `x` berisi semua kolom kecuali 'HeartDisease'.
x = dataset.drop(['HeartDisease'], axis=1)
y = dataset['HeartDisease']
#Variabel `y` menyimpan target (output) yang akan diprediksi oleh model.
# `dataset['HeartDisease']` memilih kolom 'HeartDisease' dari DataFrame `dataset`.
# Jadi, `y` berisi hanya nilai-nilai dari kolom 'HeartDisease'.

In [19]:
from sklearn.model_selection import train_test_split
# Mengimpor fungsi `train_test_split` dari modul `sklearn.model_selection`.
# Fungsi ini digunakan untuk membagi data menjadi data latih dan data uji.

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=8)
# Membagi data fitur (`x`) dan target (`y`) menjadi data latih dan data uji

In [20]:
# Mengimpor kelas SVC (Support Vector Classifier) dari modul sklearn.svm.
# SVC digunakan untuk membangun model klasifikasi Support Vector Machine.
from sklearn.svm import SVC

# Membuat objek model SVC dengan nama 'model'.
model = SVC()
# Melatih model SVC menggunakan data latih (x_train dan y_train).
model.fit(x_train, y_train)

SVC()

In [21]:
# Membuat array NumPy bernama 'seseorang' yang berisi data satu individu.
# Data tersebut merepresentasikan fitur-fitur (input) untuk model machine learning.
# Fitur-fitur tersebut kemungkinan adalah: Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope
seseorang = np.array([[57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1]])

# Memprediksi status penyakit jantung ('HeartDisease') untuk 'seseorang' menggunakan model yang telah dilatih.
print(model.predict(seseorang))

[0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [22]:
# Mengimpor fungsi accuracy_score dari library sklearn.metrics
from sklearn.metrics import accuracy_score

# Memprediksi target (HeartDisease) untuk data latih (x_train) menggunakan model yang sudah dilatih
y_pred = model.predict(x_train)
# Mencetak akurasi model pada data latih.
print(accuracy_score(y_train, y_pred))

# Memprediksi target (HeartDisease) untuk data uji (x_test) menggunakan model yang sudah dilatih.
y_pred_test = model.predict(x_test)
# Mencetak akurasi model pada data uji.
print(accuracy_score(y_test, y_pred_test))

0.7320872274143302
0.6884057971014492


In [23]:
# Mengimpor GridSearchCV dari sklearn.model_selection
from sklearn.model_selection import GridSearchCV

# Mendefinisikan parameter yang akan dicoba oleh GridSearchCV.
# 'C', 'gamma', dan 'kernel' adalah parameter untuk model SVC.
params = {'C': [0.1, 1, 10, 100],
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ['rbf', 'linear']}

# Membuat objek GridSearchCV dengan model SVC, parameter yang akan diuji
grid = GridSearchCV(SVC(), params, refit=True, verbose=3)
# Melatih GridSearchCV dengan data latih (x_train dan y_train).
grid.fit(x_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.550 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.550 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.555 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.555 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.555 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.829 total time=   0.6s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.853 total time=   0.5s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.852 total time=   0.2s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.844 total time=   0.3s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.883 total time=   0.6s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.550 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'linear']},
             verbose=3)

In [24]:
# mencetak skor terbaik yang dicapai oleh model selama proses Grid Search.
print(grid.best_score_)

0.8551477713178294


In [25]:
# Baris ini mengambil parameter terbaik yang ditemukan oleh GridSearchCV.
# - `grid.best_estimator_`: Mengacu pada model terbaik yang ditemukan selama proses pencarian.
best_params = grid.best_estimator_.get_params()

# Loop ini akan mengiterasi setiap parameter yang didefinisikan di `params`
# Baris ini mencetak nama parameter (`param`) dan nilai terbaiknya (`best_params[param]`) yang ditemukan oleh GridSearchCV.
for param in params:
    print(f"{param} : {best_params[param]}")

C : 1
gamma : 1
kernel : linear
